const RECIPES_FETCH_REQUEST = '[recipes] FETCH_REQUEST';
const RECIPES_FETCH_SUCCESS = '[recipes] FETCH_SUCCESS';
const RECIPES_FETCH_ERROR = '[recipes] FETCH_ERROR';

const ADD_RECIPE_ITEM_FETCH_REQUEST = '[recipeItem_add] FETCH_REQUEST';
const ADD_RECIPE_ITEM_FETCH_SUCCESS = '[recipeItem__add] FETCH_SUCCESS';
const ADD_RECIPE_ITEM_FETCH_ERROR = '[recipeItem__add] FETCH_ERROR';

export default {
  RECIPES_FETCH_REQUEST,
  RECIPES_FETCH_SUCCESS,
  RECIPES_FETCH_ERROR,
  ADD_RECIPE_ITEM_FETCH_REQUEST,
  ADD_RECIPE_ITEM_FETCH_SUCCESS,
  ADD_RECIPE_ITEM_FETCH_ERROR,
};
